# Generated by Django 5.2.7 on 2025-11-13 17:38

import django.db.models.deletion
import django.db.models.functions.datetime
import promise_tracker.common.fields
import promise_tracker.common.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the legislative institution.', max_length=255, verbose_name='Name')),
                ('institution_type', models.CharField(choices=[('Parliament', 'Parliament'), ('Council', 'Council')], help_text='The type of legislative institution.', max_length=50, verbose_name='Type')),
                ('institution_level', models.CharField(choices=[('National', 'National'), ('Regional', 'Regional'), ('State City', 'State City')], help_text='The level of the legislative institution.', max_length=50, verbose_name='Level')),
                ('logo', promise_tracker.common.fields.UploadImageField(blank=True, help_text='The logo of the legislative institution.', null=True, validators=[promise_tracker.common.validators.ImageValidator(), promise_tracker.common.validators.FileSizeValidator()], verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legislative Institution',
                'verbose_name_plural': 'Legislative Institutions',
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'unique': 'A political party %(value)s already exists.'}, help_text='The name of the political party.', max_length=255, unique=True, verbose_name='Name')),
                ('email', models.EmailField(help_text='The contact email of the political party.', max_length=255, verbose_name='E-pasts')),
                ('established_date', models.DateField(help_text='The date when the political party was established.', verbose_name='Established Date')),
                ('liquidated_date', models.DateField(blank=True, help_text='The date when the political party was liquidated, if applicable.', null=True, verbose_name='Liquidated Date')),
                ('ideologies', promise_tracker.common.fields.CommaSeparatedField(blank=True, error_messages={'empty_item_not_allowed': 'Ideology array is not valid!'}, help_text='The ideologies associated with the political party, separated by commas.', null=True, validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=255)], verbose_name='Ideologies')),
                ('logo', promise_tracker.common.fields.UploadImageField(blank=True, help_text='The logo of the political party.', null=True, validators=[promise_tracker.common.validators.ImageValidator(), promise_tracker.common.validators.FileSizeValidator()], verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Political Party',
                'verbose_name_plural': 'Political Parties',
            },
        ),
        migrations.CreateModel(
            name='PoliticalUnion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'unique': 'A political union %(value)s already exists.'}, help_text='The name of the political union.', max_length=255, unique=True, verbose_name='Name')),
                ('email', models.EmailField(help_text='The contact email of the political union.', max_length=255, verbose_name='E-pasts')),
                ('established_date', models.DateField(help_text='The date when the political union was established.', verbose_name='Established Date')),
                ('liquidated_date', models.DateField(blank=True, help_text='The date when the political union was liquidated, if applicable.', null=True, verbose_name='Liquidated Date')),
                ('ideologies', promise_tracker.common.fields.CommaSeparatedField(blank=True, error_messages={'empty_item_not_allowed': 'Ideology array is not valid!'}, help_text='The ideologies associated with the political union, separated by commas.', null=True, validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=255)], verbose_name='Ideologies')),
                ('logo', promise_tracker.common.fields.UploadImageField(blank=True, help_text='The logo of the political union.', null=True, validators=[promise_tracker.common.validators.ImageValidator(), promise_tracker.common.validators.FileSizeValidator()], verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parties', models.ManyToManyField(help_text='The political parties that are part of this union.', related_name='unions', to='classifiers.politicalparty', verbose_name='Parties')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Political Union',
                'verbose_name_plural': 'Political Unions',
            },
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(error_messages={'unique': 'A convocation %(value)s already exists.'}, help_text='The name of the convocation.', max_length=255, unique=True, verbose_name='Name')),
                ('start_date', models.DateField(help_text='The start date of the convocation.', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='The end date of the convocation, if applicable.', null=True, verbose_name='End Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('legislative_institution', models.ForeignKey(help_text='The legislative institution associated with this convocation.', on_delete=django.db.models.deletion.PROTECT, related_name='convocations', to='classifiers.legislativeinstitution', verbose_name='Legislative Institution')),
                ('political_parties', models.ManyToManyField(help_text='The political parties participating in this convocation.', related_name='convocations', to='classifiers.politicalparty', verbose_name='Political Parties')),
                ('political_unions', models.ManyToManyField(help_text='The political unions participating in this convocation.', related_name='convocations', to='classifiers.politicalunion', verbose_name='Political Unions')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
            },
        ),
        migrations.AddConstraint(
            model_name='legislativeinstitution',
            constraint=models.UniqueConstraint(fields=('name', 'institution_type', 'institution_level'), name='unique_institution_name_type_level', violation_error_message='A legislative institution with the same name, type and level already exists.'),
        ),
        migrations.AddConstraint(
            model_name='politicalparty',
            constraint=models.CheckConstraint(condition=models.Q(('liquidated_date__isnull', True), ('liquidated_date__gte', models.F('established_date')), _connector='OR'), name='liquidated_date_gte_established_date', violation_error_message='Liquidated date is smaller than established date.'),
        ),
        migrations.AddConstraint(
            model_name='politicalparty',
            constraint=models.CheckConstraint(condition=models.Q(('established_date__lte', django.db.models.functions.datetime.Now())), name='established_date_lte_today', violation_error_message='Established date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='politicalparty',
            constraint=models.CheckConstraint(condition=models.Q(('liquidated_date__isnull', True), ('liquidated_date__lte', django.db.models.functions.datetime.Now()), _connector='OR'), name='liquidated_date_lte_today', violation_error_message='Liquidated date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='politicalunion',
            constraint=models.CheckConstraint(condition=models.Q(('liquidated_date__isnull', True), ('liquidated_date__gte', models.F('established_date')), _connector='OR'), name='union_liquidated_date_gte_established_date', violation_error_message='Liquidated date is smaller than established date.'),
        ),
        migrations.AddConstraint(
            model_name='politicalunion',
            constraint=models.CheckConstraint(condition=models.Q(('established_date__lte', django.db.models.functions.datetime.Now())), name='union_established_date_lte_today', violation_error_message='Established date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='politicalunion',
            constraint=models.CheckConstraint(condition=models.Q(('liquidated_date__isnull', True), ('liquidated_date__lte', django.db.models.functions.datetime.Now()), _connector='OR'), name='union_liquidated_date_lte_today', violation_error_message='Liquidated date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='convocation',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='convocation_end_date_gte_start_date', violation_error_message='End date is smaller than start date.'),
        ),
        migrations.AddConstraint(
            model_name='convocation',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', django.db.models.functions.datetime.Now())), name='convocation_start_date_lte_today', violation_error_message='Start date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='convocation',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__lte', django.db.models.functions.datetime.Now()), _connector='OR'), name='convocation_end_date_lte_today', violation_error_message='End date is in the future.'),
        ),
    ]
