# Generated by Django 5.2.7 on 2025-11-15 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='legislativeinstitution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='legislativeinstitution',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='legislativeinstitution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='legislativeinstitution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='legislativeinstitution',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
