# Generated by Django 5.2.7 on 2025-12-02 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convocation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='convocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='convocation',
            name='political_parties',
            field=models.ManyToManyField(help_text='The political parties participating in this convocation.', related_name='convocations', to='classifiers.politicalparty', verbose_name='Political Parties'),
        ),
        migrations.AddConstraint(
            model_name='politicalparty',
            constraint=models.CheckConstraint(condition=models.Q(('liquidated_date__isnull', True), ('liquidated_date__gte', models.F('established_date')), _connector='OR'), name='liquidated_date_gte_established_date', violation_error_message='Liquidated date is smaller than established date.'),
        ),
        migrations.AddConstraint(
            model_name='convocation',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='convocation_end_date_gte_start_date', violation_error_message='End date is smaller than start date.'),
        ),
    ]
