# Generated by Django 5.2.7 on 2025-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_alter_convocation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='ideologies',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Center-Left', 'Center-Left'), ('Center', 'Center'), ('Center-Right', 'Center-Right'), ('Right', 'Right'), ('Libertarian', 'Libertarian'), ('Green', 'Green'), ('Far-Right', 'Far-Right'), ('Far-Left', 'Far-Left'), ('Populist', 'Populist')], help_text='The ideology of the political party.', max_length=50, null=True, verbose_name='Ideologies'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='ideologies',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Center-Left', 'Center-Left'), ('Center', 'Center'), ('Center-Right', 'Center-Right'), ('Right', 'Right'), ('Libertarian', 'Libertarian'), ('Green', 'Green'), ('Far-Right', 'Far-Right'), ('Far-Left', 'Far-Left'), ('Populist', 'Populist')], help_text='The ideology of the political union.', max_length=50, null=True, verbose_name='Ideologies'),
        ),
    ]
