# Generated by Django 5.2.7 on 2025-11-22 17:02

import promise_tracker.common.fields
import promise_tracker.common.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0003_alter_politicalparty_ideologies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='ideologies',
            field=promise_tracker.common.fields.CommaSeparatedField(blank=True, error_messages={'empty_item_not_allowed': 'Ideology array is not valid!'}, help_text='The ideologies associated with the political party, separated by commas.', null=True, validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=255)], verbose_name='Ideologies'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='ideologies',
            field=promise_tracker.common.fields.CommaSeparatedField(blank=True, error_messages={'empty_item_not_allowed': 'Ideology array is not valid!'}, help_text='The ideologies associated with the political union, separated by commas.', null=True, validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=255)], verbose_name='Ideologies'),
        ),
    ]
