# Generated by Django 5.2.7 on 2025-11-22 17:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_alter_politicalparty_ideologies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='ideologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Left', 'Left'), ('Center-Left', 'Center-Left'), ('Center', 'Center'), ('Center-Right', 'Center-Right'), ('Right', 'Right'), ('Libertarian', 'Libertarian'), ('Green', 'Green'), ('Far-Right', 'Far-Right'), ('Far-Left', 'Far-Left'), ('Populist', 'Populist')], help_text='The ideologies associated with the political party, separated by commas.', max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='ideologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Left', 'Left'), ('Center-Left', 'Center-Left'), ('Center', 'Center'), ('Center-Right', 'Center-Right'), ('Right', 'Right'), ('Libertarian', 'Libertarian'), ('Green', 'Green'), ('Far-Right', 'Far-Right'), ('Far-Left', 'Far-Left'), ('Populist', 'Populist')], help_text='The ideologies associated with the political union, separated by commas.', max_length=88, null=True, verbose_name='Ideologies'),
        ),
        migrations.AlterField(
            model_name='politicalunion',
            name='name',
            field=models.CharField(choices=[('Left', 'Left'), ('Center-Left', 'Center-Left'), ('Center', 'Center'), ('Center-Right', 'Center-Right'), ('Right', 'Right'), ('Libertarian', 'Libertarian'), ('Green', 'Green'), ('Far-Right', 'Far-Right'), ('Far-Left', 'Far-Left'), ('Populist', 'Populist')], error_messages={'unique': 'A political union %(value)s already exists.'}, help_text='The name of the political union.', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
