# Generated by Django 5.2.7 on 2025-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0006_remove_convocation_convocation_start_date_lte_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalunion',
            name='name',
            field=models.CharField(error_messages={'unique': 'A political union %(value)s already exists.'}, help_text='The name of the political union.', max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
