# Generated by Django 5.2.7 on 2025-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_baseuser_is_deleted_alter_baseuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether the record has been soft deleted.', verbose_name='Is Deleted'),
        ),
    ]
