# Generated by Django 5.2.7 on 2025-11-18 18:56

import promise_tracker.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(help_text='The email address of the user.', max_length=255, unique=True, validators=[promise_tracker.common.validators.CustomEmailValidator()], verbose_name='E-pasta adrese'),
        ),
    ]
