# Generated by Django 5.2.7 on 2025-11-18 19:02

import promise_tracker.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_baseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, help_text='The email address of the user.', max_length=255, unique=True, validators=[promise_tracker.common.validators.CustomEmailValidator()], verbose_name='E-pasta adrese'),
        ),
    ]
