# Generated by Django 5.2.7 on 2025-12-02 14:02

import django.db.models.deletion
import promise_tracker.common.fields
import promise_tracker.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='The name of the promise result.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(help_text='A detailed description of the promise result.', verbose_name='Description')),
                ('sources', promise_tracker.common.fields.CommaSeparatedField(error_messages={'empty_item_not_allowed': 'Sources list is not valid.', 'null': 'Sources are null.'}, help_text='A comma-separated list of sources related to the promise result.', validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=1000, min_items=1)], verbose_name='Sources')),
                ('date', models.DateField(help_text='The date when the promise result was determined.', verbose_name='Date')),
                ('is_final', models.BooleanField(default=False, help_text='Indicates whether this is the final result for the promise.', verbose_name='Is Final')),
                ('status', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], help_text='The status of the promise result.', max_length=20, null=True, verbose_name='Status')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The review status of the promise result.', max_length=20, verbose_name='Review Status')),
                ('review_date', models.DateTimeField(blank=True, help_text='The date and time when the promise result was reviewed.', null=True, verbose_name='Review Date')),
            ],
            options={
                'verbose_name': 'Promise Result',
                'verbose_name_plural': 'Promise Results',
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='The name of the promise.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(help_text='A detailed description of the promise.', verbose_name='Description')),
                ('sources', promise_tracker.common.fields.CommaSeparatedField(error_messages={'empty_item_not_allowed': 'Sources list is not valid.', 'null': 'Sources are null.'}, help_text='A comma-separated list of sources related to the promise.', validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=1000, min_items=1)], verbose_name='Sources')),
                ('date', models.DateField(help_text='The date when the promise was made.', verbose_name='Date')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The review status of the promise.', max_length=20, verbose_name='Review Status')),
                ('review_date', models.DateTimeField(blank=True, help_text='The date and time when the promise was reviewed.', null=True, verbose_name='Review Date')),
                ('convocation', models.ForeignKey(help_text='The convocation during which this promise was made.', on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='classifiers.convocation', verbose_name='Convocation')),
            ],
            options={
                'verbose_name': 'Promise',
                'verbose_name_plural': 'Promises',
            },
        ),
    ]
