# Generated by Django 5.2.7 on 2025-11-17 13:49

import django.db.models.deletion
import django.db.models.functions.datetime
import promise_tracker.common.fields
import promise_tracker.common.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0002_alter_convocation_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='The name of the promise.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(help_text='A detailed description of the promise.', verbose_name='Description')),
                ('sources', promise_tracker.common.fields.CommaSeparatedField(error_messages={'empty_item_not_allowed': 'Sources list is not valid.', 'null': 'Sources are null.'}, help_text='A comma-separated list of sources related to the promise.', validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=1000, min_items=1)], verbose_name='Sources')),
                ('date', models.DateField(help_text='The date when the promise was made.', verbose_name='Date')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The review status of the promise.', max_length=20, verbose_name='Review Status')),
                ('review_date', models.DateTimeField(blank=True, help_text='The date and time when the promise was reviewed.', null=True, verbose_name='Review Date')),
                ('convocation', models.ForeignKey(help_text='The convocation during which this promise was made.', on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='classifiers.convocation', verbose_name='Convocation')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('party', models.ForeignKey(blank=True, help_text='The political party associated with this promise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='classifiers.politicalparty', verbose_name='Political Party')),
                ('reviewer', models.ForeignKey(blank=True, help_text='The user who reviewed the promise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_promises', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('union', models.ForeignKey(blank=True, help_text='The political union associated with this promise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='classifiers.politicalunion', verbose_name='Political Union')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Promise',
                'verbose_name_plural': 'Promises',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether the record has been soft deleted.', verbose_name='Is Deleted')),
                ('content', models.TextField(help_text='The content of the comment.', verbose_name='Content')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('response_to', models.ForeignKey(blank=True, help_text='The comment this comment is responding to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='promises.comment', verbose_name='Response To')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('promise', models.ForeignKey(help_text='The promise associated with this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='promises.promise', verbose_name='Promise')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='PromiseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='The name of the promise result.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(help_text='A detailed description of the promise result.', verbose_name='Description')),
                ('sources', promise_tracker.common.fields.CommaSeparatedField(error_messages={'empty_item_not_allowed': 'Sources list is not valid.', 'null': 'Sources are null.'}, help_text='A comma-separated list of sources related to the promise result.', validators=[promise_tracker.common.validators.CommaSeparatedStringValidator(max_item_length=1000, min_items=1)], verbose_name='Sources')),
                ('date', models.DateField(help_text='The date when the promise result was determined.', verbose_name='Date')),
                ('is_final', models.BooleanField(default=False, help_text='Indicates whether this is the final result for the promise.', verbose_name='Is Final')),
                ('status', models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], help_text='The status of the promise result.', max_length=20, null=True, verbose_name='Status')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The review status of the promise result.', max_length=20, verbose_name='Review Status')),
                ('review_date', models.DateTimeField(blank=True, help_text='The date and time when the promise result was reviewed.', null=True, verbose_name='Review Date')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('promise', models.ForeignKey(help_text='The promise associated with this result.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='promises.promise', verbose_name='Promise')),
                ('reviewer', models.ForeignKey(blank=True, help_text='The user who reviewed the promise result.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_promise_results', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Promise Result',
                'verbose_name_plural': 'Promise Results',
            },
        ),
        migrations.AddConstraint(
            model_name='promise',
            constraint=models.CheckConstraint(condition=models.Q(('date__lte', django.db.models.functions.datetime.Now())), name='promise_date_not_in_future', violation_error_message='Promise date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='promise',
            constraint=models.CheckConstraint(condition=models.Q(('party__isnull', False), ('union__isnull', False), _connector='OR'), name='promise_party_or_union_not_null', violation_error_message='Nether party nor union is set.'),
        ),
        migrations.AddConstraint(
            model_name='promise',
            constraint=models.CheckConstraint(condition=models.Q(('party__isnull', True), ('union__isnull', True), _connector='OR'), name='promise_party_xor_union', violation_error_message='Both party and union are set.'),
        ),
        migrations.AddConstraint(
            model_name='promise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('review_status', 'PENDING'), _negated=True), ('review_date__isnull', False)), models.Q(('review_status', 'PENDING'), ('review_date__isnull', True)), _connector='OR'), name='promise_review_date_status_consistency', violation_error_message='Inconsistent review date and status.'),
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(('date__lte', django.db.models.functions.datetime.Now())), name='promiseresult_date_not_in_future', violation_error_message='Promise result date is in the future.'),
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_final', True), ('status__isnull', False)), ('is_final', False), _connector='OR'), name='promiseresult_final_status_consistency', violation_error_message='Final promise result status is not set.'),
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('review_status', 'PENDING'), _negated=True), ('review_date__isnull', False)), models.Q(('review_status', 'PENDING'), ('review_date__isnull', True)), _connector='OR'), name='promiseresult_review_date_status_consistency', violation_error_message='Inconsistent review date and status.'),
        ),
    ]
