# Generated by Django 5.2.7 on 2025-12-02 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifiers', '0002_initial'),
        ('promises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='promise',
            name='party',
            field=models.ForeignKey(blank=True, help_text='The political party associated with this promise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='classifiers.politicalparty', verbose_name='Political Party'),
        ),
        migrations.AddField(
            model_name='promise',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The user who reviewed the promise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_promises', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AddField(
            model_name='promise',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='promiseresult',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='promiseresult',
            name='promise',
            field=models.ForeignKey(help_text='The promise associated with this result.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='promises.promise', verbose_name='Promise'),
        ),
        migrations.AddField(
            model_name='promiseresult',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The user who reviewed the promise result.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_promise_results', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AddField(
            model_name='promiseresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddConstraint(
            model_name='promise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('review_status', 'PENDING'), _negated=True), ('review_date__isnull', False)), models.Q(('review_status', 'PENDING'), ('review_date__isnull', True)), _connector='OR'), name='promise_review_date_status_consistency', violation_error_message='Inconsistent review date and status.'),
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_final', True), ('status__isnull', False)), ('is_final', False), _connector='OR'), name='promiseresult_final_status_consistency', violation_error_message='Final promise result status is not set.'),
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('review_status', 'PENDING'), _negated=True), ('review_date__isnull', False)), models.Q(('review_status', 'PENDING'), ('review_date__isnull', True)), _connector='OR'), name='promiseresult_review_date_status_consistency', violation_error_message='Inconsistent review date and status.'),
        ),
    ]
