# Generated by Django 5.2.7 on 2025-11-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promise',
            name='promise_date_not_in_future',
        ),
        migrations.RemoveConstraint(
            model_name='promiseresult',
            name='promiseresult_date_not_in_future',
        ),
    ]
