# Generated by Django 5.2.7 on 2025-12-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_initial'),
        ('promises', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='party',
            field=models.ForeignKey(help_text='The political party associated with this promise.', on_delete=django.db.models.deletion.PROTECT, related_name='promises', to='classifiers.politicalparty', verbose_name='Political Party'),
        ),
    ]
