# Generated by Django 5.2.7 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_remove_promise_promise_date_not_in_future_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='The content of the comment.', max_length=2000, verbose_name='Content'),
        ),
    ]
