# Generated by Django 5.2.7 on 2025-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0003_alter_promise_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='description',
            field=models.TextField(help_text='A detailed description of the promise.', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promiseresult',
            name='description',
            field=models.TextField(help_text='A detailed description of the promise result.', max_length=2000, verbose_name='Description'),
        ),
    ]
