# Generated by Django 5.2.7 on 2025-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0004_alter_promise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='name',
            field=models.CharField(help_text='The name of the promise.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='promiseresult',
            unique_together={('promise', 'is_final')},
        ),
    ]
