# Generated by Django 5.2.7 on 2025-12-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0005_alter_promise_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promiseresult',
            unique_together={('promise', 'name')},
        ),
    ]
