# Generated by Django 5.2.7 on 2025-12-09 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0006_alter_promiseresult_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promiseresult',
            name='promiseresult_final_status_consistency',
        ),
        migrations.AlterField(
            model_name='promise',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The review status of the promise.', max_length=20, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='promiseresult',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='The review status of the promise result.', max_length=20, verbose_name='Review status'),
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_final', True), ('status__isnull', False)), models.Q(('is_final', False), ('status__isnull', True)), _connector='OR'), name='promiseresult_final_status_consistency', violation_error_message='Final promise result status is not set.'),
        ),
    ]
