# Generated by Django 5.2.7 on 2025-12-11 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0007_remove_promiseresult_promiseresult_final_status_consistency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promiseresult',
            name='promiseresult_final_status_consistency',
        ),
        migrations.AddConstraint(
            model_name='promiseresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_final', True), ('status__isnull', False)), ('is_final', False), _connector='OR'), name='promiseresult_final_status_consistency', violation_error_message='Final promise result status is not set.'),
        ),
    ]
